### ISSUE TITLE
Tensorflow compatibility with CUDA & cuDNN

### ISSUE THREAD

**Issue by hungpowang** [shouhaiel1/CNN-LSTM-Violence-detection#1]
Hi,

I'm trying to run predict_video1/2.py. I got a tensorflow error of "Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR". It seems to be a compatibility issue. Could you tell me your version of Tensorflow, CUDA,  and cuDNN? 

Thank you!!!

**Comment by souhaiel1** [comment]
Hi , that is definitely a compatibility issue .. I am using Tensorflow 2.4.0rc1 , cuda 10.1 (i am currently on the 451.67 version of the drivers) and cudnn 10.1 .

**Comment by hungpowang** [comment]
> Hi , that is definitely a compatibility issue .. I am using Tensorflow 2.4.0rc1 , cuda 10.1 (i am currently on the 451.67 version of the drivers) and cudnn 10.1 .

Hi, many thanks for your reply. I've downgraded my CUDA from 10.2 to 10.1. But I think the version of your cuDNN might be 7.x.x. Could you simply use instruction `$ cat /usr/local/cuda/include/cudnn.h | grep CUDNN_MAJOR -A 2` to check again? There should be CUDNN_MAJOR, CUDNN_MINOR, and CUDNN_PATCHLEVEL to represent the version.

**Comment by hungpowang** [comment]
I've solved the tensorflow error of "Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR". It caused by over allocate GPU memory and can be resolved by setting "tf.GPUOptions" to limit the memory usage.
